/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ProcessedComment as PrismaProcessedComment,
} from "@prisma/client";

export class ProcessedCommentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ProcessedCommentCountArgs, "select">
  ): Promise<number> {
    return this.prisma.processedComment.count(args);
  }

  async processedComments(
    args: Prisma.ProcessedCommentFindManyArgs
  ): Promise<PrismaProcessedComment[]> {
    return this.prisma.processedComment.findMany(args);
  }
  async processedComment(
    args: Prisma.ProcessedCommentFindUniqueArgs
  ): Promise<PrismaProcessedComment | null> {
    return this.prisma.processedComment.findUnique(args);
  }
  async createProcessedComment(
    args: Prisma.ProcessedCommentCreateArgs
  ): Promise<PrismaProcessedComment> {
    return this.prisma.processedComment.create(args);
  }
  async updateProcessedComment(
    args: Prisma.ProcessedCommentUpdateArgs
  ): Promise<PrismaProcessedComment> {
    return this.prisma.processedComment.update(args);
  }
  async deleteProcessedComment(
    args: Prisma.ProcessedCommentDeleteArgs
  ): Promise<PrismaProcessedComment> {
    return this.prisma.processedComment.delete(args);
  }
}
